### ISSUE TITLE
Implement `MediaStreamTrack.getSettings` on native

### ISSUE THREAD

**Issue by SleepySquash** [instrumentisto/flutter-webrtc#17]
**Is your feature request related to a problem? Please describe.**
Вызов `getSettings` над `MediaStreamTrack`ом необходим для того, чтобы определить `deviceId`, который используется на данном треке. Этот `deviceId` считается выбранным видео/аудио устройством при первой инициализации треков, чтобы в списке устройств в дальнейшем корректно отображать выбранное устройство.

**Describe the solution you'd like**
Web реализация у `getSettings` имеется, а нативной реализации данной функции нет. Хотелось бы, чтобы эта функция была и чтобы она в первую очередь возвращала как минимум `deviceId`. Из остальных параметров используются пока только `width` и `height`, но желательно, чтобы возвращались все реализованные под вебом параметры.

**Comment by alexlapa** [comment]
`MediaStreamTrack` has `deviceId` getter, and video track dimensions can be inspected only if track is rendered via `VideoRenderer`.
